-- Run this in the Supabase SQL Editor

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  position text not null check (position in ('GK','CB','LB','RB','CDM','CM','CAM','LW','RW','ST')),
  pace int not null check (pace between 1 and 99),
  shooting int not null check (shooting between 1 and 99),
  passing int not null check (passing between 1 and 99),
  dribbling int not null check (dribbling between 1 and 99),
  defending int not null check (defending between 1 and 99),
  physical int not null check (physical between 1 and 99),
  created_at timestamptz default now()
);

create table if not exists public.practice_matches (
  id bigint generated by default as identity primary key,
  match_date date not null,
  home_team text not null default 'Orange',
  away_team text not null default 'Green',
  home_score int not null default 0 check (home_score >= 0),
  away_score int not null default 0 check (away_score >= 0),
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.external_matches (
  id bigint generated by default as identity primary key,
  match_date date not null,
  opponent_name text not null,
  venue text not null check (venue in ('Home','Away','Neutral')),
  our_score int not null default 0 check (our_score >= 0),
  opponent_score int not null default 0 check (opponent_score >= 0),
  competition text,
  notes text,
  created_at timestamptz default now()
);

alter table public.players add column if not exists position text;
alter table public.practice_matches add column if not exists notes text;
alter table public.external_matches add column if not exists notes text;

alter table public.players enable row level security;
alter table public.practice_matches enable row level security;
alter table public.external_matches enable row level security;

drop policy if exists "public read players" on public.players;
create policy "public read players" on public.players for select to anon, authenticated using (true);

drop policy if exists "public read practice" on public.practice_matches;
create policy "public read practice" on public.practice_matches for select to anon, authenticated using (true);

drop policy if exists "public read external" on public.external_matches;
create policy "public read external" on public.external_matches for select to anon, authenticated using (true);

drop policy if exists "authenticated manage players" on public.players;
create policy "authenticated manage players" on public.players for all to authenticated using (true) with check (true);

drop policy if exists "authenticated manage practice" on public.practice_matches;
create policy "authenticated manage practice" on public.practice_matches for all to authenticated using (true) with check (true);

drop policy if exists "authenticated manage external" on public.external_matches;
create policy "authenticated manage external" on public.external_matches for all to authenticated using (true) with check (true);

-- Extra policies/fixes for delete + goal scorers
create table if not exists public.goal_scorers (
  id bigint generated by default as identity primary key,
  match_type text not null,
  match_id text not null,
  player_name text not null,
  goals int not null default 1 check (goals >= 1),
  created_at timestamptz default now()
);

alter table public.goal_scorers enable row level security;

drop policy if exists "public read goal scorers" on public.goal_scorers;
create policy "public read goal scorers" on public.goal_scorers for select to anon, authenticated using (true);

drop policy if exists "authenticated manage goal scorers" on public.goal_scorers;
create policy "authenticated manage goal scorers" on public.goal_scorers for all to authenticated using (true) with check (true);

alter table public.players enable row level security;
alter table public.practice_matches enable row level security;
alter table public.external_matches enable row level security;

drop policy if exists "authenticated manage players" on public.players;
create policy "authenticated manage players" on public.players for all to authenticated using (true) with check (true);

drop policy if exists "authenticated manage practice" on public.practice_matches;
create policy "authenticated manage practice" on public.practice_matches for all to authenticated using (true) with check (true);

drop policy if exists "authenticated manage external" on public.external_matches;
create policy "authenticated manage external" on public.external_matches for all to authenticated using (true) with check (true);
